spring.application.name=Agendamente-Servicos-carro

# ============================================================
# Configuracao do banco de dados PostgreSQL - Supabase
# ============================================================
spring.datasource.url=jdbc:postgresql://db.maqbzawjpozykyzskymu.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=8&hasdalsd6/o
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Configuracoes para executar o data.sql
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ============================================================
# Configuracao do banco de dados MongoDB Atlas - Auditoria
# ============================================================
spring.mongodb.uri=mongodb+srv://brunosfs_db_user:n3Y7FKq9C1126LXr@cluster0.bm67cwy.mongodb.net/?appName=Cluster0
spring.mongodb.database=auditoria