spring.application.name=Agendamente-Servicos-carro

spring.datasource.url=jdbc:postgresql://localhost:5432/agendamento_carros
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
#https://tzfiopdljvnmlsrxzagp.supabase.co:

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update